from fake_useragent import UserAgent

headers = {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate, br",
    "Accept-Language": "en-GB,en;q=0.9",
    "BNC-Location": "",
    "clienttype": "web",
    "Connection": "keep-alive",
    "Content-Length": "402",
    "Content-Type": "application/json",
    "Host": "www.binance.com",
    "lang": "en",
    "Origin": "https://www.binance.com",
    "Referer": "https://www.binance.com/en/game/tg/moon-bix",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "same-origin",
    "User-Agent": UserAgent(os="android").random,
#     "X-PASSTHROUGH-TOKEN": "",
    #     "BNC-UUID": "571f38a7-6677-439e-b7c3-c782aa668a2b",
    #     "X-TRACE-ID": "",
    #     "X-UI-REQUEST-TRACE": "",
    #     "Cookie": "",
    #     "csrftoken": "",
    #     "device-info": "",
    #     "FVIDEO-ID": "",
    #     "FVIDEO-TOKEN": "",
}
